### ISSUE TITLE
Spring Cloud Bus

### ISSUE THREAD

**Issue by udhos** [Piszmog/cloudconfigclient#63]
Hi,

I am currently refactoring some Go applications to retrieve configuration from SCCS, and this **cloudconfigclient** module has been really useful to me. Thank you for it!

For my cases, one missing piece of the puzzle about making Go applications to work with SCCS was to support [Spring Cloud Bus](https://www.baeldung.com/spring-cloud-bus) in order to get automatic config refresh notifications.

Then I put this small lib in place to help with receiving config refresh notifications from SCCS:

https://github.com/udhos/refresh: refresh delivers Spring Cloud Config Bus refresh notifications to Go applications

Hope it might be useful to you as well!

Thanks again!

**Comment by Piszmog** [comment]
Hey @udhos, sorry taking so long to look at this. Glad this library has be useful to you.

That refresh library seems really useful - good job!

For my library's purpose, I want to keep the area of concern solely focused on retrieving configurations and resources from the Config Server. Listening for refresh notifications and handling those notifications should live within another library (such as yours).

Thank you for letting my know about your refresh library?
