### ISSUE TITLE
support labels

### ISSUE THREAD

**Issue by TristanHorlamus** [Piszmog/cloudconfigclient#67]
### Issue Description
missing ability to use label
https://docs.spring.io/spring-cloud-config/docs/current/reference/html/

### Steps to Reproduce
the `GetConfiguration` method does not accept `label` as 3rd parameter and therefore won't be able to build a path to call SCC with a specific label as shown on spring cloud config documentation:
`/{application}/{profile}[/{label}]`

suggestion is to introduce a second function (to be backward compatible) `GetConfigurationWithLabel` that allows for a 3rd parameter to be used and added at the end of the path

### Expected Behavior
calling `GetConfiguraitonWithLabel` will apply the provided label and pull the spring cloud config from the selected label (branch-name / tag)

**Comment by Piszmog** [comment]
Closed by #68
